name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf libtool
    - name: Generate configure script (if needed)
      run: autoreconf -i || true
    - name: Configure
      run: ./configure || { echo "Configure failed"; exit 1; }
    - name: Build project
      run: make
    - name: Run tests
      run: make check || true
    - name: Verify distribution
      run: make distcheck || true
