name: C/C++ CI

on:
  push:
    branches: [ "main" ]  # تشغيل الـ workflow عند دفع التعديلات إلى الفرع الرئيسي
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest  # تشغيل البناء على نظام Ubuntu

    steps:
    - uses: actions/checkout@v4  # تنزيل الكود من المستودع

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential  # تثبيت الأدوات الأساسية مثل المترجم gcc

    - name: Build project using Makefile
      run: make  # استخدام make لبناء المشروع بناءً على Makefile الموجود في المجلد الجذر

    - name: Run tests
      run: make check  # إذا كان لديك خطوة لاختبار المشروع باستخدام make

    - name: Clean build files
      run: make clean  # تنظيف الملفات الناتجة بعد كل عملية بناء
