name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # يتم التشغيل على Ubuntu افتراضيًا، وعلى macOS فقط عند بناء iOS.
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    # 1. تنزيل الكود
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. إعداد Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # يمكنك تحديد إصدار ثابت مثل '3.13.0'

    # 3. تثبيت الاعتماديات
    - name: Install Dependencies
      run: flutter pub get

    # 4. تشغيل الاختبارات
    - name: Run Tests
      run: flutter test

    # 5. بناء APK للأندرويد
    - name: Build APK
      run: flutter build apk --release
      if: matrix.os == 'ubuntu-latest'

    # 6. التحقق من وجود APK
    - name: Verify APK Exists
      run: test -f build/app/outputs/flutter-apk/app-release.apk
      if: matrix.os == 'ubuntu-latest'

    # 7. بناء iOS (في حالة تشغيل على macOS فقط)
    - name: Build iOS
      run: flutter build ios --release
      if: matrix.os == 'macos-latest'

    # 8. رفع النتائج (Artifacts)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: flutter-build
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/ios/ipa # يمكنك تعديل المسار إذا كنت تستخدم iOS
      if: success()
