name: Build and Deploy Flutter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. تنزيل الكود من مستودع GitHub
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. إعداد Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # تأكد من أنك تستخدم الإصدار الذي تحتاجه

    # 3. تحديث Flutter (اختياري)
    - name: Upgrade Flutter
      run: flutter upgrade

    # 4. تثبيت التبعيات
    - name: Install dependencies
      run: flutter pub get

    # 5. بناء المشروع (تأكد من أنك في المجلد الصحيح)
    - name: Build project
      run: flutter build apk --release

    # 6. رفع الملفات الناتجة (APK)
    - name: Upload Built APK
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk  # تأكد من المسار هنا
