name: Build and Deploy Flutter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. تنزيل الكود
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. إعداد Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'

    # 3. تثبيت التبعيات
    - name: Install dependencies
      run: flutter pub get

    # 4. بناء المشروع
    - name: Build project
      run: flutter build apk

    # 5. رفع الملفات الناتجة باستخدام الإصدار الصحيح (v3)
    - name: Upload Built APK
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk
