name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze Default Scheme
    runs-on: macos-latest

    steps:
      # 1. تنزيل الكود
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. تحديد الـ Scheme الافتراضية
      - name: Set Default Scheme
        id: set-scheme
        run: |
          SCHEME=$(xcodebuild -list -json | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['targets'][0]")
          echo "SCHEME=$SCHEME" >> $GITHUB_ENV
          echo Using default scheme: $SCHEME

      # 3. بناء وتحليل المشروع
      - name: Build and Analyze
        run: |
          # تحديد نوع الملف (xcworkspace أو xcodeproj)
          if [[ -f *.xcworkspace ]]; then
            FILETYPE="workspace"
            FILE=$(ls *.xcworkspace)
          elif [[ -f *.xcodeproj ]]; then
            FILETYPE="project"
            FILE=$(ls *.xcodeproj)
          else
            echo "No Xcode project or workspace found!" && exit 1
          fi

          # تشغيل أمر البناء والتحليل
          xcodebuild clean build analyze \
            -scheme "$SCHEME" \
            -"$FILETYPE" "$FILE" | xcpretty
