name: Xcode - Build, Analyze, and Makefile CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze Default Scheme
    runs-on: macos-latest  # سيتم تشغيله على macOS

    steps:
      # 1. تنزيل الكود
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. تحديد الـ Scheme الافتراضية
      - name: Set Default Scheme
        id: set-scheme
        run: |
          SCHEME=$(xcodebuild -list -json | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['targets'][0]")
          echo "SCHEME=$SCHEME" >> $GITHUB_ENV
          echo Using default scheme: $SCHEME

      # 3. بناء وتحليل المشروع باستخدام Xcode
      - name: Build and Analyze
        run: |
          # تحديد نوع الملف (xcworkspace أو xcodeproj)
          if [[ -f *.xcworkspace ]]; then
            FILETYPE="workspace"
            FILE=$(ls *.xcworkspace)
          elif [[ -f *.xcodeproj ]]; then
            FILETYPE="project"
            FILE=$(ls *.xcodeproj)
          else
            echo "No Xcode project or workspace found!" && exit 1
          fi

          # تشغيل أمر البناء والتحليل
          xcodebuild clean build analyze \
            -scheme "$SCHEME" \
            -"$FILETYPE" "$FILE" | xcpretty

      # 4. تشغيل Makefile إذا كان موجودًا (يمكنك تخصيص هذه الخطوة)
      - name: Run Makefile build
        run: make
        if: success()

      # 5. رفع الملفات الناتجة (اختياري)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xcode-build-artifacts
          path: build/  # رفع نتائج البناء مثل الملفات أو التقارير
